"""Tests for the detailed Word memory generated by ``diseno-apoyos-neopreno``."""

from pathlib import Path
from zipfile import ZipFile

from bridge_design.domain.simple_neoprene_support import (
    ExternalSteelPlatePair,
    FixedBarGroup,
    SimpleNeopreneGeometry,
    SimpleSupportDemands,
    SimpleSupportInputs,
    climate_temperature,
    design_simple_neoprene_support,
)
from bridge_design.reporting import simple_neoprene_docx


def _movable_result():
    return design_simple_neoprene_support(
        SimpleSupportInputs(
            support_type="MOVIL_PLACAS",
            geometry=SimpleNeopreneGeometry(60.0, 40.0, 5.0),
            demands=SimpleSupportDemands(
                r_dc_tn=20.0,
                r_dw_tn=1.18,
                r_pl_tn=0.0,
                r_ll_im_tn=29.42,
                pga=0.0,
                fpga=1.08,
                span_length_m=15.0,
                temperature=climate_temperature("costa", 20.0),
            ),
            plates=ExternalSteelPlatePair(thickness_cm=2.54),
            fc_kg_cm2=280.0,
        )
    )


def _fixed_result():
    return design_simple_neoprene_support(
        SimpleSupportInputs(
            support_type="FIJO_BARRAS",
            geometry=SimpleNeopreneGeometry(60.0, 40.0, 5.0),
            demands=SimpleSupportDemands(
                r_dc_tn=20.0,
                r_dw_tn=1.18,
                r_pl_tn=0.0,
                r_ll_im_tn=29.42,
                h_long_tn=4.87,
                pga=0.48,
                fpga=1.08,
                span_length_m=15.0,
                temperature=climate_temperature("costa", 20.0),
            ),
            fixed_bars=FixedBarGroup(),
            fc_kg_cm2=280.0,
        )
    )


def test_movable_neoprene_report_is_detailed_a4_word_memory(tmp_path: Path) -> None:
    output = simple_neoprene_docx.generate_simple_neoprene_docx(
        _movable_result(),
        tmp_path / "memoria_apoyo_movil.docx",
    )
    payload = output.read_bytes()
    assert payload.startswith(b"PK")
    assert len(payload) > 40_000

    with ZipFile(output) as package:
        assert package.testzip() is None
        xml = package.read("word/document.xml").decode("utf-8")
        styles = package.read("word/styles.xml").decode("utf-8")

    assert "Memoria de cálculo" in xml
    assert "del apoyo de neopreno simple" in xml
    assert "Reemplazando los valores correspondientes" in xml
    assert "Factor de forma" in xml
    assert "Movimiento térmico de contracción" in xml
    assert "Fuerza horizontal por corte del neopreno móvil" in xml
    assert "Friccion disponible" in xml or "Fricción disponible" in xml
    assert "m:oMath" in xml
    assert "m:f" in xml
    assert 'w:top="1440"' in xml
    assert "Arial Narrow" in styles


def test_fixed_neoprene_report_includes_pin_interaction(tmp_path: Path) -> None:
    output = simple_neoprene_docx.generate_simple_neoprene_docx(
        _fixed_result(),
        tmp_path / "memoria_apoyo_fijo.docx",
    )
    xml = ZipFile(output).read("word/document.xml").decode("utf-8")
    assert "Interacción corte-flexión del pasador" in xml
    assert "Demanda horizontal de diseño del apoyo fijo" in xml
    assert "pasadores lisos" in xml or "Pasadores" in xml


def test_cancelled_neoprene_save_dialog_does_not_write_report(monkeypatch) -> None:
    monkeypatch.setattr(
        simple_neoprene_docx,
        "select_simple_neoprene_docx_save_path",
        lambda result=None: None,
    )
    assert simple_neoprene_docx.generate_simple_neoprene_docx_with_dialog(_movable_result()) is None
