"""Tests for the detailed Word memory generated by ``diseno-estribos`` and ``diseno-muros``."""

from pathlib import Path
from zipfile import ZipFile

from bridge_design.domain.abutment import AbutmentGeometryInputs, AbutmentInputs, solve_abutment_design
from bridge_design.reporting import abutment_docx


def test_abutment_report_is_detailed_a4_word_memory(tmp_path: Path) -> None:
    output = abutment_docx.generate_abutment_docx(
        solve_abutment_design(),
        tmp_path / "memoria_estribo.docx",
    )
    payload = output.read_bytes()
    assert payload.startswith(b"PK")
    assert len(payload) > 100_000

    with ZipFile(output) as package:
        assert package.testzip() is None
        xml = package.read("word/document.xml").decode("utf-8")
        styles = package.read("word/styles.xml").decode("utf-8")

    assert "Memoria de cálculo" in xml
    assert "del estribo de puente" in xml
    assert "Reemplazando los valores correspondientes" in xml
    assert "Coeficiente activo de Coulomb" in xml
    assert "Coeficiente sísmico Mononobe-Okabe kAE" in xml
    assert "arctan" in xml
    assert "Inventario vertical factorizado" in xml
    assert "Presión admisible factorizada" in xml
    assert "Límite de excentricidad" in xml
    assert "Origen de Mu y Vu" in xml
    assert "As,R" in xml
    assert "φ=0.90" in xml
    assert "2.7.1.1.4.2a" in xml
    assert "Resultantes factorizadas" in xml
    assert "Verificación al deslizamiento" in xml
    assert "Presión de contacto estructural y Meyerhof" in xml
    assert "Expresión Ai" in xml
    assert "0.5PIR" in xml
    assert "2.8.1.1.14.1" in xml
    assert "γEQ" in xml
    assert "max(0.5PAE,EH)+PIR" in xml or "max(0.5" in xml
    assert "750" in xml
    assert "2.9.1.4.5.8" in xml
    assert "As,adic" in xml
    assert "smax,pat" in xml
    assert "Altura teórica de corte ht" in xml
    assert "Lcort" in xml
    assert "2.9.1.5.6.3.4.2" in xml or "Procedimiento general" in xml
    assert "123000" in xml
    assert "36.629" in xml
    assert "71.294" not in xml
    assert "Estado q" in xml
    assert "Diseño estructural" in xml
    assert "Control de fisuración" in xml
    assert "Cuadro de barras" in xml
    assert "Comentario técnico" not in xml
    assert "páginas PDF" not in xml
    assert "m:oMath" in xml
    assert "m:f" in xml
    assert 'w:sz w:val="44"' in xml
    assert 'w:top="1440"' in xml
    assert 'w:right="1440"' in xml
    assert 'w:bottom="1440"' in xml
    assert 'w:left="1440"' in xml
    assert "Arial Narrow" in styles
    assert 'w:sz w:val="22"' in styles
    assert 'w:color w:val="000000"' in styles
    assert 'w:line="360"' in styles


def test_cancelled_abutment_save_dialog_does_not_write_report(monkeypatch) -> None:
    monkeypatch.setattr(abutment_docx, "select_abutment_docx_save_path", lambda result=None: None)
    assert abutment_docx.generate_abutment_docx_with_dialog(solve_abutment_design()) is None


def test_pure_wall_report_is_detailed_a4_word_memory(tmp_path: Path) -> None:
    wall_inputs = AbutmentInputs(
        geometry=AbutmentGeometryInputs(
            retained_height_m=7.8,
            footing_width_m=6.0,
            footing_thickness_m=0.95,
            toe_length_m=2.55,
            lower_stem_thickness_m=0.95,
            upper_stem_thickness_m=0.40,
            front_soil_depth_m=2.50,
        ),
        is_pure_wall=True,
    )
    result = solve_abutment_design(wall_inputs)
    assert result.stem_reinforcement_cut is not None
    output = abutment_docx.generate_abutment_docx(
        result,
        tmp_path / "memoria_muro.docx",
    )
    payload = output.read_bytes()
    assert payload.startswith(b"PK")
    assert len(payload) > 100_000

    with ZipFile(output) as package:
        assert package.testzip() is None
        xml = package.read("word/document.xml").decode("utf-8")
        header = package.read("word/header1.xml").decode("utf-8")

    assert "Memoria de cálculo" in xml
    assert "del muro en cantilever" in xml
    assert "MURO EN CANTILEVER" in header
    assert "del estribo de puente" not in xml
    assert "Acciones transferidas por el tablero" not in xml
    assert "Estabilidad del muro" in xml
    assert "Condición con puente" not in xml
    assert "Condición sin puente" not in xml
    assert "Fuerza inercial del muro y combinaciones MTC PAE/PIR" in xml
    assert "PEQ superestructura" not in xml
    assert "2.9.1.4.5.8" in xml
    assert "As,adic" in xml
    assert "Altura teórica de corte ht" in xml
    assert "2.9.1.5.6.3.4.2" in xml or "Procedimiento general" in xml
    assert "Verificación de cortante" in xml
    assert "Cuadro de barras" in xml
